name: github pages

env:
  SLACK_INVITE_URL: ${{ secrets.SLACK_INVITE_URL }}

on:
  workflow_dispatch:
  push:
    branches:
      - main # Set a branch to deploy
  schedule:
    - cron: 0 5 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Generate Sponsors 💚🏢
        uses: naltatis/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GH_API_TOKEN_ORG }}
          file: "layouts/shortcodes/sponsors.html"
          minimum: 500
          organization: true
          marker: org-sponsors

      - name: Generate Sponsors 💚🙋‍♂️
        uses: naltatis/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          file: "layouts/shortcodes/sponsors.html"
          minimum: 500
          organization: false
          marker: andig-sponsors

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
